### ISSUE TITLE
Does not install with Laravel 5.2

### ISSUE THREAD

**Issue by jakobjp** [rokde/laravel-bootstrap-formbuilder#1]
This library has a requirement for 5.1.\* in the composer.json, but newest Laravel is 5.2.x.

Would i be possible to upgrade this? The Laravel Collective HTML lib works with 5.2

**Comment by rokde** [comment]
Can you make a pull request?

**Comment by danhunsaker** [comment]
I've got this covered.  See PR #2.

**Comment by rokde** [comment]
Release r0.0.6 does it have
